# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='src_id',
            field=models.CharField(default='source unidentified', max_length=255),
        ),
        migrations.AddField(
            model_name='logs',
            name='type',
            field=models.CharField(default='none type', max_length=255),
        ),
        migrations.AlterField(
            model_name='logs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
