# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0003_logs_when_happened'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_id', models.CharField(default='source unidentified', max_length=255)),
                ('error_type', models.CharField(default='None', max_length=255)),
                ('danger_status', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('when_happened', models.DateField(default='1980-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='LogAttempts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_id', models.CharField(default='source unidentified', max_length=255)),
                ('was_successful', models.BooleanField(default=False)),
                ('when_happened', models.DateField(default='1980-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ServerDown',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_id', models.CharField(default='source unidentified', max_length=255)),
                ('how_long', models.IntegerField(default=0)),
                ('when_happened', models.DateField(default='1980-01-01')),
            ],
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
