# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0004_auto_20161027_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationChanged',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_id', models.CharField(default='unknown', max_length=255)),
                ('description', models.CharField(default='None', max_length=255)),
                ('when_happened', models.DateField(default='1980-01-01')),
            ],
        ),
        migrations.DeleteModel(
            name='ServerDown',
        ),
        migrations.AlterField(
            model_name='errors',
            name='error_type',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='errors',
            name='src_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='logattempts',
            name='src_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
