# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0005_auto_20161027_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationchanged',
            old_name='src_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='configurationchanged',
            old_name='when_happened',
            new_name='when',
        ),
        migrations.RenameField(
            model_name='errors',
            old_name='danger_status',
            new_name='danger',
        ),
        migrations.RenameField(
            model_name='errors',
            old_name='src_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='errors',
            old_name='when_happened',
            new_name='when',
        ),
        migrations.RenameField(
            model_name='errors',
            old_name='error_type',
            new_name='why',
        ),
        migrations.RenameField(
            model_name='logattempts',
            old_name='was_successful',
            new_name='succeeded',
        ),
        migrations.RenameField(
            model_name='logattempts',
            old_name='src_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='logattempts',
            old_name='when_happened',
            new_name='when',
        ),
    ]
