# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0006_auto_20161029_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationchanged',
            old_name='type',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='errors',
            old_name='type',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='logattempts',
            old_name='type',
            new_name='source',
        ),
    ]
