# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0007_auto_20161029_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationchanged',
            old_name='when',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='errors',
            old_name='when',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='logattempts',
            old_name='when',
            new_name='event_date',
        ),
    ]
